package com.wadpam.survey.dao;

import com.wadpam.survey.domain.DAnswer;
import com.wadpam.survey.domain.DQuestion;
import com.wadpam.survey.domain.DResponse;
import com.wadpam.survey.domain.DSurvey;
import com.wadpam.survey.domain.DVersion;

import java.util.Collection;

/**
 * Business Methods interface for entity DAnswer.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-10-19T08:40:22.845+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DAnswerDao extends GeneratedDAnswerDao {

    Iterable<DAnswer> queryByResponseIds(Collection<Long> ids);

    Iterable<Long> queryKeysBySurvey(DSurvey survey);

    Iterable<Long> queryKeysByResponse(DResponse response);

    Iterable<Long> queryKeysByVersion(DVersion version);

    Iterable<Long> queryKeysByQuestion(DQuestion question);

}
