package com.wadpam.survey.dao;

/**
 * Business Methods interface for entity Di18n.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-10-19T08:53:11.620+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface Di18nDao extends GeneratedDi18nDao {

	// TODO: declare your Business Methods here
	
}
