package com.wadpam.survey.dao;

import com.wadpam.survey.domain.DQuestion;
import com.wadpam.survey.domain.DSurvey;
import com.wadpam.survey.domain.DVersion;

/**
 * Business Methods interface for entity DOption.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-10-22T13:08:12.502+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DOptionDao extends GeneratedDOptionDao {
    
    void setMemCacheEntities(boolean memCacheEntities);

    Iterable<Long> queryKeysBySurvey(DSurvey survey);

    Iterable<Long> queryKeysByVersion(DVersion version);

    Iterable<Long> queryKeysByQuestion(DQuestion question);
    
}
