package com.wadpam.survey.dao;

/**
 * Implementation of Business Methods related to entity DOption.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-10-22T13:08:12.502+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DOptionDaoBean 
	extends GeneratedDOptionDaoImpl
		implements DOptionDao 
{

    @Override
    public void setMemCacheEntities(boolean memCacheEntities) {
        this.memCacheEntities = memCacheEntities;
    }

}
