package com.wadpam.survey.dao;

import net.sf.mardao.core.Filter;

import com.wadpam.survey.domain.DQuestion;
import com.wadpam.survey.domain.DSurvey;
import com.wadpam.survey.domain.DVersion;

/**
 * Implementation of Business Methods related to entity DOption.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-10-22T13:08:12.502+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DOptionDaoBean 
	extends GeneratedDOptionDaoImpl
		implements DOptionDao 
{

    @Override
    public void setMemCacheEntities(boolean memCacheEntities) {
        this.memCacheEntities = memCacheEntities;
    }

    @Override
    public Iterable<Long> queryKeysBySurvey(DSurvey survey) {
        Filter filter = createEqualsFilter(COLUMN_NAME_SURVEY, survey);
        return queryIterableKeys(0, 0, null, null, null, false, null, false, filter);
    }

    @Override
    public Iterable<Long> queryKeysByVersion(DVersion version) {
        Filter filter = createEqualsFilter(COLUMN_NAME_VERSION, version);
        return queryIterableKeys(0, 0, null, null, null, false, null, false, filter);
    }

    @Override
    public Iterable<Long> queryKeysByQuestion(DQuestion question) {
        Filter filter = createEqualsFilter(COLUMN_NAME_QUESTION, question);
        return queryIterableKeys(0, 0, null, null, null, false, null, false, filter);
    }
}
