package com.wadpam.survey.dao;

import net.sf.mardao.core.Filter;

/**
 * Implementation of Business Methods related to entity DOption.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-10-22T13:08:12.502+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DOptionDaoBean 
	extends GeneratedDOptionDaoImpl
		implements DOptionDao 
{

    @Override
    public void setMemCacheEntities(boolean memCacheEntities) {
        this.memCacheEntities = memCacheEntities;
    }

    @Override
    public Iterable<Long> queryKeysBySurvey(Object surveyKey) {
        Filter filter = createEqualsFilter(COLUMN_NAME_SURVEY, surveyKey);
        return queryIterableKeys(0, -1, null, null, null, false, null, false, filter);
    }

    @Override
    public Iterable<Long> queryKeysByVersion(Object versionKey) {
        Filter filter = createEqualsFilter(COLUMN_NAME_VERSION, versionKey);
        return queryIterableKeys(0, -1, null, null, null, false, null, false, filter);
    }

    @Override
    public Iterable<Long> queryKeysByQuestion(Object questionKey) {
        Filter filter = createEqualsFilter(COLUMN_NAME_QUESTION, questionKey);
        return queryIterableKeys(0, -1, null, null, null, false, null, false, filter);
    }
}
