package com.wadpam.survey.dao;

import com.wadpam.survey.domain.DSurvey;
import com.wadpam.survey.domain.DVersion;

/**
 * Business Methods interface for entity DQuestion.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-10-19T08:40:22.845+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DQuestionDao extends GeneratedDQuestionDao {

    void setMemCacheEntities(boolean memCacheEntities);

    Iterable<Long> queryKeysBySurvey(DSurvey survey);

    Iterable<Long> queryKeysByVersion(DVersion version);
	
}
