package com.wadpam.survey.dao;

import net.sf.mardao.core.Filter;

import com.wadpam.survey.domain.DSurvey;
import com.wadpam.survey.domain.DVersion;

/**
 * Implementation of Business Methods related to entity DQuestion. This (empty) class is generated by mardao, but edited by
 * developers. It is not overwritten by the generator once it exists.
 * 
 * Generated on 2012-10-19T08:40:22.845+0700.
 * 
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DQuestionDaoBean extends GeneratedDQuestionDaoImpl implements DQuestionDao {

    @Override
    public void setMemCacheEntities(boolean memCacheEntities) {
        this.memCacheEntities = memCacheEntities;
    }

    @Override
    public Iterable<Long> queryKeysBySurvey(DSurvey survey) {
        Filter filter = createEqualsFilter(COLUMN_NAME_SURVEY, survey);
        return queryIterableKeys(0, 0, null, null, null, false, null, false, filter);
    }

    @Override
    public Iterable<Long> queryKeysByVersion(DVersion version) {
        Filter filter = createEqualsFilter(COLUMN_NAME_VERSION, version);
        return queryIterableKeys(0, 0, null, null, null, false, null, false, filter);
    }
}
