package com.wadpam.survey.dao;

/**
 * Implementation of Business Methods related to entity DSurvey.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-10-18T16:20:14.354+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DSurveyDaoBean 
	extends GeneratedDSurveyDaoImpl
		implements DSurveyDao 
{

    @Override
    public void setMemCacheEntities(boolean memCacheEntities) {
        this.memCacheEntities = memCacheEntities;
    }

}
