package com.wadpam.survey.dao;

/**
 * Business Methods interface for entity DSurvey.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-10-18T16:20:14.354+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DSurveyDao extends GeneratedDSurveyDao {

    void setMemCacheEntities(boolean memCacheEntities);
	
}
