package com.wadpam.survey.dao;

import com.wadpam.survey.domain.DSurvey;

/**
 * Business Methods interface for entity DVersion.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-06-04T17:55:36.016+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DVersionDao extends GeneratedDVersionDao {

    void setMemCacheEntities(boolean memCacheEntities);

    Iterable<Long> queryKeysBySurvey(DSurvey survey);
}
