package com.wadpam.survey.dao;

/**
 * Implementation of Business Methods related to entity DVersion.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-11-19T14:21:50.040+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DVersionDaoBean 
	extends GeneratedDVersionDaoImpl
		implements DVersionDao 
{

	// TODO: implement your Business Methods here

}
